[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]

[settings.pipx]
uvx = true

[tools]
# tools
github-cli = 'latest'
glab = 'latest'
helm = 'latest'
k9s = 'latest'
kubectl = 'latest'
poetry = 'latest'
pre-commit = 'latest'
ruff = 'latest'
uv = 'latest'

# pipx tools
"pipx:copier" = "latest"
"pipx:django-language-server" = "latest"
"pipx:djlint" = "latest"
"pipx:ipython" = "latest"
"pipx:isort" = "latest"
"pipx:mypy" = "latest"
"pipx:pipx" = "latest"
"pipx:pytest" = "latest"
"pipx:tox" = "latest"
"pipx:ty" = "latest"
"pipx:pytest-language-server" = "latest"

# runtimes (needs to be last)
go = 'latest'
node = 'latest'
python = ['3.14', '3.13', '3.12', '3.11', '3.10']
rust = 'latest'

[tasks."docker:prune"]
description = 'Docker prune'
run = """
if [ -z "$(docker ps -q)" ]; then
  echo "No running containers"
else
  echo "Stopping all running containers..."
  docker stop $(docker ps -a -q) || true
fi
docker system prune -f
docker image prune -a -f
docker builder prune -a -f
docker buildx prune -a -f
"""

[tasks."docker:prune-all"]
depends = ["docker:prune"]
description = 'Docker prune all'
run = """
docker volume prune -a -f
"""